---
title: "Initial Communities Tree Map"
author: "Louis Goodall"
date: "2024-09-01"
output: pdf_document:
  latex_engine: xelatex
---

```{r}
library(tidyverse)
library(terra)
library(sf)
library(rFIA)
library(data.table)
library(tinytex)
options(scipen = 999)
setwd("/Users/louisgoodall/Desktop/HOLY FUCK A PHD/The Big One/For Testing")
```

# NEW PIEDMONT

```{r}
treeMap <- rast('/Users/louisgoodall/Desktop/HOLY FUCK A PHD/The Big One/For Testing/TreeMap 2014/Data/national_c2014_tree_list.tif')
crs(treeMap) <- "EPSG:5070"
Piedmont.shp <- st_read("/Users/louisgoodall/Desktop/HOLY FUCK A PHD/The Big One/Parameterisation/NC Ecoregions & Projections/Level 3/nc_eco_l3.shp") %>%
  st_transform(crs = crs(treeMap))

# Crop treeMap and fill in NAs as 0s, this is also needed for the projection to work
treeMap <- crop(treeMap, Piedmont.shp)
treeMap[is.na(treeMap)] <- 0
treeMap <- project(treeMap, "EPSG:26917", method = "near")

rastTemplate <- rast(extent = treeMap,
                     resolution = 70.71068,
                     crs = "EPSG:26917")
treeMap <- resample(treeMap, rastTemplate, method = "near")

plot_counts <- table(values(treeMap)) %>% as.data.frame()

tl_plots <- data.table::fread('/Users/louisgoodall/Desktop/HOLY FUCK A PHD/The Big One/For Testing/TreeMap 2014/Data/TL_CN_Lookup.txt') %>%
  filter(tl_id %in% values(treeMap))

# # Gotta test to see the difference in basal area after removing other States
# tl_trees_all <- data.table::fread('/Users/louisgoodall/Desktop/HOLY FUCK A PHD/The Big One/For Testing/TreeMap 2014/Data/Tree_table_CONUS.txt') %>%
#   filter(tl_id %in% values(treeMap))

tl_trees <- data.table::fread('/Users/louisgoodall/Desktop/HOLY FUCK A PHD/The Big One/For Testing/TreeMap 2014/Data/Tree_table_CONUS.txt') %>%
  filter(tl_id %in% values(treeMap),
         State_Abbreviation %in% c("NC", "SC", "VA", "GA", "TN")) %>%
  mutate(CN = ifelse(CN == 264152945489998, 362885577489998, CN))

speciesREF <- readxl::read_excel("/Users/louisgoodall/Desktop/HOLY FUCK A PHD/The Big One/USFS Coefficients/REF_SPECIES.xlsx")

# Get the basal area by species
tl_trees_ba <- tl_trees %>%
  dplyr::group_by(tl_id, SPCD) %>%
  dplyr::summarise(plot_ba = sum(I((DIA/2)^2), na.rm = TRUE), .group = "drop") %>%
  dplyr::mutate(tl_id = as.factor(tl_id)) %>%
  dplyr::left_join(plot_counts, by = c("tl_id" = "Var1")) %>% #add column for how frequent each plot type is
  dplyr::mutate(study_area_ba = plot_ba * Freq) %>%
  dplyr::group_by(SPCD) %>%
  dplyr::summarise(species_ba_total = sum(study_area_ba)/10000) %>%
  dplyr::arrange(species_ba_total) %>%
  dplyr::left_join(dplyr::select(speciesREF, c("SPCD", "SPECIES_SYMBOL", "GENUS", "SPECIES"))) %>%
  dplyr::mutate(species_ba_pct = species_ba_total / sum(species_ba_total))

# tl_trees_ba_all <- tl_trees_all %>%
#   dplyr::group_by(tl_id, SPCD) %>%
#   dplyr::summarise(plot_ba = sum(I((DIA/2)^2), na.rm = TRUE), .group = "drop") %>%
#   dplyr::mutate(tl_id = as.factor(tl_id)) %>%
#   dplyr::left_join(plot_counts, by = c("tl_id" = "Var1")) %>% #add column for how frequent each plot type is
#   dplyr::mutate(study_area_ba = plot_ba * Freq) %>%
#   dplyr::group_by(SPCD) %>%
#   dplyr::summarise(species_ba_total = sum(study_area_ba)/10000) %>%
#   dplyr::arrange(species_ba_total) %>%
#   dplyr::left_join(dplyr::select(speciesREF, c("SPCD", "SPECIES_SYMBOL", "GENUS", "SPECIES"))) %>%
#   dplyr::mutate(species_ba_pct = species_ba_total / sum(species_ba_total))

# sum(tl_trees_ba$species_ba_total) / sum(tl_trees_ba_all$species_ba_total)
# 86.89% of the basal area is retained by using the 5 states strategy

piedmontSpp <- tl_trees_ba %>%
  arrange(desc(species_ba_pct)) %>%
  mutate(cumulativePct = cumsum(species_ba_pct)) %>%
  filter(species_ba_pct > 0.005) %>%
  mutate(SPECIES_SYMBOL == ifelse("LIST2", "LIST",
                                  ifelse(SPECIES_SYMBOL == "QUPR2", "QUMO4",
                                         ifelse(SPECIES_SYMBOL == "PIPA2", "PIPA",
                                                ifelse(SPECIES_SYMBOL == "PIEC2", "PIEC",
                                                       ifelse(SPECIES_SYMBOL == "CAAL27", "CATO6", SPECIES_SYMBOL))))))

# Object containing only the spp of interest
landscapeSpp <- piedmontSpp %>% select(SPECIES_SYMBOL) %>% arrange(SPECIES_SYMBOL)

# Loop to read in and bind 5 states TREE tables (NC,GA,VA,SC,TN)
csv_directory <- "/Users/louisgoodall/Desktop/HOLY FUCK A PHD/The Big One/FIA Data/5 States/TREE"
csv_files <- list.files(path = csv_directory, pattern = "*.csv", full.names = TRUE)
csv_list <- lapply(csv_files, fread)
treeTable5States <- rbindlist(csv_list, use.names = TRUE, fill = TRUE)
rm(csv_list)
fia_trees <- treeTable5States %>% filter(PLT_CN %in% tl_plots$CN)
rm(treeTable5States)

# COND
csv_directory <- "/Users/louisgoodall/Desktop/HOLY FUCK A PHD/The Big One/FIA Data/5 States/COND"
csv_files <- list.files(path = csv_directory, pattern = "*.csv", full.names = TRUE)
csv_list <- lapply(csv_files, fread)
condTable5States <- rbindlist(csv_list, use.names = TRUE, fill = TRUE)
rm(csv_list)
fia_cond <- condTable5States %>% filter(PLT_CN %in% tl_plots$CN)

# SITE_TREE
# This contains more tables than just the 5 states listed because we need them
# to make the age ~ diameter relationship. I start with states closest to NC
# and move further afield if I need to
csv_directory <- "/Users/louisgoodall/Desktop/HOLY FUCK A PHD/The Big One/FIA Data/5 States/SITE_TREE"
csv_files <- list.files(path = csv_directory, pattern = "*.csv", full.names = TRUE)
csv_list <- lapply(csv_files, fread)
siteTreeTable5States <- rbindlist(csv_list, use.names = TRUE, fill = TRUE)
rm(csv_list)
sitetrees <- siteTreeTable5States %>% filter(PLT_CN %in% tl_plots$CN)

# Read in CA SITETREE table. Coastal redwood (SPCD == 211) is the closest genetic species
# to the bald cypress (SPCD == 221)
sitetreesCA <- read_csv('/Users/louisgoodall/Desktop/HOLY FUCK A PHD/The Big One/FIA Data/5 States/SITE_TREE/CA_SITETREE.csv') %>% filter(SPCD == 211)
sitetrees <- rbind(sitetrees, sitetreesCA) %>% mutate(SPCD = ifelse(SPCD == 211, 221, SPCD)) # Will need to make the SPCD == 222 model from this data too

#----AGE CALCULATIONS----#
# Fit a linear regression
tree_regressions <- sitetrees %>%
  filter(!is.na(DIA) & !is.na(AGEDIA) & !is.na(SPCD)) %>%
  filter(SPCD %in% fia_trees$SPCD) %>%
  group_by(SPCD) %>%
  do(model = lm(AGEDIA ~ log(DIA) + 0, data = .)) %>%
  filter(SPCD %in% piedmontSpp$SPCD)

# Add in row for TAAS, QUPH & QULA3
# TAAS
spcd222Row <- tree_regressions %>%
  filter(SPCD == 221) %>%
  mutate(SPCD = 222)
tree_regressions <- bind_rows(tree_regressions, spcd222Row) %>%
  arrange(SPCD)
# QUPH
spcd831Row <- tree_regressions %>%
  filter(SPCD == 827) %>%
  mutate(SPCD = 831)
tree_regressions <- bind_rows(tree_regressions, spcd831Row) %>%
  arrange(SPCD)
# QULA3
spcd820Row <- tree_regressions %>%
  filter(SPCD == 827) %>%
  mutate(SPCD = 820)
tree_regressions <- bind_rows(tree_regressions, spcd820Row) %>%
  arrange(SPCD)


# NOW FIGURE OUT MISSING SPCDs
# # Find the missing species that weren't in the sitetree tables
# SPCDs <- tree_regressions$SPCD
# xSpp <- speciesREF %>% filter(SPCD %in% SPCDs) %>% arrange(SPCD) %>% select(SPECIES_SYMBOL) %>% arrange(SPECIES_SYMBOL)
# ySpp <- tl_trees_ba %>%
#   arrange(desc(species_ba_pct)) %>%
#   mutate(cumulativePct = cumsum(species_ba_pct)) %>%
#   filter(species_ba_pct > 0.005) %>%
#   select(SPECIES_SYMBOL) %>%
#   arrange(SPECIES_SYMBOL)
# 
# xSpp %>% as.vector()
# ySpp %>% as.vector()

# NYBI, NYSY, OXAR, QULA3, QUPH, TAAS
# TAAS, QUPH and QULA3 retroactively fitted above

# NYSY
# SIZE NEEDS TO BE HALVED, WATER TUPLEO WHICH THIS IS BASED OFF OF ARE TOO BIG
tree_regressions <- fia_cond %>%
  inner_join(fia_trees, by = c("PLT_CN", "INVYR", "STATECD", "UNITCD", "COUNTYCD", "PLOT", "CONDID")) %>%
  select(PLT_CN, SPCD, INVYR, STATECD, UNITCD, COUNTYCD, PLOT, CONDID, DIA, HT, SICOND, SIBASE) %>%
  filter(SPCD == 694) %>%
  mutate(SICOND = ifelse(is.na(SICOND), mean(SICOND, na.rm = TRUE), SICOND),
         AGE = (log (1-(HT/(1.3213 * SICOND^(0.9995)))^(1/(0.8549*(SICOND^(-0.0016)))))/-0.0254)) %>%
  do(model = lm(AGE ~ DIA, data = .)) %>%
  mutate(SPCD = 694) %>%
  select(SPCD, model) %>%
  rbind(tree_regressions) %>%
  arrange(SPCD)

# OXAR
tree_regressions <- fia_cond %>%
  inner_join(fia_trees, by = c("PLT_CN", "INVYR", "STATECD", "UNITCD", "COUNTYCD", "PLOT", "CONDID")) %>%
  select(PLT_CN, SPCD, INVYR, STATECD, UNITCD, COUNTYCD, PLOT, CONDID, DIA, HT, SICOND, SIBASE) %>%
  filter(SPCD == 711) %>%
  mutate(SICOND = ifelse(is.na(SICOND), mean(SICOND, na.rm = TRUE), SICOND),
         AGE = (log(1-(HT/(0.9276 * SICOND^(1.0591)))^(1/(0.3529*(SICOND^(0.3114)))))/-0.0424)) %>%
  do(model = lm(AGE ~ DIA, data = .)) %>%
  mutate(SPCD = 711) %>%
  select(SPCD, model) %>%
  rbind(tree_regressions) %>%
  arrange(SPCD)

# # PITA
# # NEEDS TO BE WORKED OUT, PITA IS TOO LOW USING SAM FLAKE METHOD
# tree_regressions <- fia_cond %>%
#   inner_join(fia_trees, by = c("PLT_CN", "INVYR", "STATECD", "UNITCD", "COUNTYCD", "PLOT", "CONDID")) %>%
#   select(PLT_CN, SPCD, INVYR, STATECD, UNITCD, COUNTYCD, PLOT, CONDID, DIA, HT, SICOND, SIBASE) %>%
#   filter(SPCD == 131) %>%
#   mutate(SICOND = ifelse(is.na(SICOND), mean(SICOND, na.rm = TRUE), SICOND),
#          AGE = (log(1-(HT/(1.1421 * SICOND^(1.0042)))^(1/(0.7632*(SICOND^(0.0358)))))/-0.0374)) %>%
#   do(model = lm(AGE ~ DIA, data = .)) %>%
#   mutate(SPCD = 131) %>%
#   select(SPCD, model) %>%
#   rbind(tree_regressions) %>%
#   arrange(SPCD)
# tree_regressions <- tree_regressions[-4,]

#----BIOMASS----#
# Check functional shape between age and diameter
fia_trees <- fia_trees %>%
  # select(SPCD, DIA) %>%
  inner_join(tree_regressions, by = "SPCD") %>%
  mutate(Age = map2_dbl(model, DIA, ~predict(.x, newdata = tibble(DIA = .y)))) %>%
  inner_join(piedmontSpp[,c(1,3)], by = "SPCD")

# This is being created because fia_trees is for some reason saving
# as a weirdly large file (146.1 GB)
plottingTable <- fia_trees %>% select(Age, SPECIES_SYMBOL)

ggplot(plottingTable, aes(x = SPECIES_SYMBOL, y = Age, fill = SPECIES_SYMBOL)) +
  geom_boxplot() +
  theme_classic() +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5)) +
  ylim(0,100)

# # Quick test to see a histogram of the PITA ages
# x <- fia_trees %>% filter(SPECIES_SYMBOL == "PITA")
# hist(x$Age)
hist(fia_trees$Age)

# Clean data and create breaks
breaks <- seq(0, 110, 10)

# Calculate cohort biomass
site_biomass <- fia_trees %>%
  mutate(biomass_area = DRYBIO_AG * TPA_UNADJ) %>%
  mutate(Age = ifelse(Age < 1, 1, Age)) %>%
  mutate(bin = cut(Age, breaks = breaks, labels = breaks[-1], right = TRUE),
         bin = as.integer(as.character(bin))) %>%
  group_by(PLT_CN, SPCD, bin) %>%
  summarise(biomass = sum(biomass_area)) %>%
  mutate(biomass = round(biomass, digits = 0),
         biomass = biomass * 0.11) # convert from lb/ac to g/m2
names(site_biomass) <- c("PLT_CN", "SPCD", "CohortAge", "CohortBiomass")

# Remove fia_trees because it is weirdly large
rm(fia_trees)

# Calculate site total biomass
site_total_biomass <- site_biomass %>%
  group_by(PLT_CN) %>%
  summarise(total_biomass = sum(CohortBiomass, na.rm = TRUE)) %>%
  mutate(total_biomass_tonnes_ha = total_biomass * 0.01)

# Get the MapCode for each unique one
site_total_biomass2 <- site_total_biomass %>%
  mutate(MapCode = tl_plots[match(PLT_CN, tl_plots$CN), "tl_id"])

# MapCodeDf for the entire NC Piedmont region, not the clipped landscape
MapCodeDf <- site_total_biomass2 %>%
  unnest(MapCode) %>%
  mutate(ID = 1:length(unique(tl_id))) %>%
  left_join(site_biomass, by = "PLT_CN") %>%
  select(PLT_CN, ID, SPCD, CohortAge, CohortBiomass, tl_id) %>%
  `colnames<-`(c("PLT_CN", "MapCode", "SPCD", "CohortAge", "CohortBiomass", "tl_id"))
MapCodeDf$PLT_CN <- as.numeric(MapCodeDf$PLT_CN)

# Read in plot tables for all 50 states 
plot_directory <- '/Users/louisgoodall/Desktop/HOLY FUCK A PHD/The Big One/FIA Data/5 States/PLOT'
csv_files <- list.files(path = plot_directory, pattern = "*.csv", full.names = TRUE)
plotDf <- do.call(rbind, lapply(csv_files, read_csv))

# Read in the clipped landscape and then apply it to treeMap
clippedPiedmont.Shp <- st_read('/Users/louisgoodall/Desktop/HOLY FUCK A PHD/Miscellaneous/Clipped Shapefile/clippedHUC.shp')
clippedTreeMap <- terra::crop(treeMap, clippedPiedmont.Shp) %>%
  mask(., clippedPiedmont.Shp)

# Merge PLOT tables with MapCodeDf
mergedMapCode <- plotDf %>%
  left_join(MapCodeDf, by = c("CN" = "PLT_CN")) %>%
  filter(!is.na(tl_id))

# merged MapCode only contains PLT_CNs that come from GA, NC, SC, TN & VA
sort(unique(mergedMapCode$STATECD))

# 3536 unique tl_ids in the whole Piedmont
mergedMapCode %>% select(tl_id) %>% arrange(tl_id) %>% unique()

# 721 unique tl_ids in the clipped Piedmont
valuesClippedTreeMap <- values(clippedTreeMap) %>%
  as.data.frame() %>%
  drop_na() %>%
  unique() %>%
  arrange(tl_id)

# There is sufficient data in the MapCode columns once it has been filtered down to the
# values from valuesClippedTreeMap
# tl_ids that are both 5 States and in clippedTreeMap
fiveStatesTLID <- mergedMapCode %>%
  filter(tl_id %in% valuesClippedTreeMap$tl_id) %>%
  select(tl_id) %>%
  unique() %>%
  arrange(tl_id)

# TESTING, convert Piedmont.shp to UTM17N crs
Piedmont.shp.UTM17N <- Piedmont.shp %>% st_transform(crs = "EPSG:26917")

# All those cells in green are tl_ids that are in the clipped landscape, so they
# should be good
test <- ifel(treeMap %in% fiveStatesTLID$tl_id, 1, 2)
plot(mask(test, Piedmont.shp.UTM17N), col = c("green", "black"))
plot(clippedPiedmont.Shp, col = NA, add = TRUE)

# All 1s are tl_ids that are from the 5 states and should be good
testTwo <- ifel(clippedTreeMap %in% fiveStatesTLID$tl_id, 1, 2)
plot(testTwo)

# Pre look at clippedTreeMap
plot(clippedTreeMap)

# Get values pre filter
valuesPreClip <- values(clippedTreeMap) %>% as.data.frame() %>% drop_na() %>% filter(tl_id > 0)

# Filter out the non 5 state tl_ids
clippedTreeMap <- ifel(clippedTreeMap %in% fiveStatesTLID$tl_id, clippedTreeMap, NA)

# Get values post filter
valuesPostClip <- values(clippedTreeMap) %>% as.data.frame() %>% drop_na()

# How many cells are lost by filtering out the non-5 State cells
# length(valuesPostClip$tl_id) / length(valuesPreClip$tl_id) # 96.69%

# Create clipped version of MapCodeDf that is only 5 state tl_ids
# STILL SEEMS ALL GOOD SO FAR
# TODO SWITCH TO MAPCODES, FOR NOW I WILL USE THE TL_IDs, BUT THEY HAVE TOO HIGH

# Some CohortBiomass values are NAs and need to be filled with the median values
# grouped by SPCD and CohortAge
medianBiomassValues <- mergedMapCode %>%
  filter(tl_id %in% valuesPostClip$tl_id,
         !is.na(CohortAge)) %>%
  select(CN, MapCode, SPCD, CohortAge, CohortBiomass, tl_id) %>%
  group_by(SPCD, CohortAge) %>%
  summarise(medianBiomass = median(CohortBiomass, na.rm = TRUE))

clippedMapCodeDf <- mergedMapCode %>%
  filter(tl_id %in% valuesPostClip$tl_id) %>%
  select(CN, MapCode, SPCD, CohortAge, CohortBiomass, tl_id) %>%
  arrange(MapCode) %>%
  mutate(MapCode = cumsum(MapCode != lag(MapCode, default = first(MapCode) -1)))

clippedMapCodeDf <- clippedMapCodeDf %>%
  left_join(medianBiomassValues, by = c("SPCD", "CohortAge")) %>%
  mutate(CohortBiomass = coalesce(CohortBiomass, medianBiomass)) %>%
  select(-medianBiomass) %>%
  drop_na()

# Turns out it just needed 3 columns, tl_id is needed twice, from, to, (the range of values), becomes!
clippedMapCodeMatrix <- clippedMapCodeDf[,c(6,6,2)] %>% as.matrix()


# Get the finalTreeMap# Get the finalTreeMapMapCodeDf
# TODO, switch the plot values over to MapCode rather than tl_id, for now
# I will just use the tl_id as the MapCode
finalTreeMap <- terra::classify(clippedTreeMap, rcl = clippedMapCodeMatrix)

writeRaster(finalTreeMap,
            filename = '/Users/louisgoodall/Desktop/HOLY FUCK A PHD/The Big One/Chapter 2/Tree Map Outputs/finalTreeMap.tif',
            NAflag = NA,
            overwrite = TRUE,
            datatype = "INT4S")

finalMapCodeDf <- clippedMapCodeDf %>%
  inner_join(speciesREF, by = "SPCD") %>%
  select(tl_id, SPECIES_SYMBOL, CohortAge, CohortBiomass) %>%
  `colnames<-`(c("MapCode", "SpeciesName", "CohortAge", "CohortBiomass"))

write_csv(finalMapCodeDf, '/Users/louisgoodall/Desktop/HOLY FUCK A PHD/The Big One/Chapter 2/Tree Map Outputs/finalMapCodeDf.csv')

```







